DOCKER_IMAGE_NAME?=eagafonov/docker-python-templete
DOCKER_IMAGE_TAG?=latest

DOCKER_IMAGE:=$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)

DOCKER_RUN_IMAGE_EXTRA_ARGS?=

docker-build: requirements.txt
	docker build -t $(DOCKER_IMAGE) -f docker/Dockerfile .

requirements.txt:
	@echo "Creating empty requirements.txt. Do not forget update it"
	touch requirements.txt

		
requirements-dev.txt:
	@echo "Creating empty requirements-dev.txt. Do not forget update it"
	touch requirements-dev.txt

docker-upgrade-requirements: docker-build requirements-dev.txt 
	touch requirements.tmp

	docker run -ti --rm \
		-v `pwd`/requirements-dev.txt:/requirements-dev.txt:ro \
		-v `pwd`/requirements.tmp:/requirements.tmp \
		--user root \
		$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) \
		/bin/sh -c 'pip install -U -r /requirements-dev.txt && pip freeze > /requirements.tmp'

	(echo "# Generated by pip freeze. Do not edit" ; sort requirements.tmp) | tee requirements.txt
	rm requirements.tmp

	# Build image again
	$(MAKE) docker-build

docker-shell:
	docker run -ti --rm \
		$(DOCKER_RUN_IMAGE_EXTRA_ARGS) \
		$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) \
		/bin/sh